# -*- coding: utf-8 -*-
"""diabetics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G20_m5I_aEl3Lp3rw_p4nfqOu4YFUsDg
"""

import pandas as pd

df=pd.read_csv("/content/diabetes.csv")

df

x=df.iloc[:,0:8].values
y=df.iloc[:,8].values

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

x_test.shape

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

x_test

from sklearn.linear_model import LogisticRegression

Log = LogisticRegression()

Log.fit(x_train,y_train)

y_pred=Log.predict(x_test)

y_pred

y_test

from sklearn.metrics import accuracy_score, confusion_matrix

accuracy_score(y_test,y_pred)

confusion_matrix(y_test,y_pred)

from sklearn.metrics import classification_report

cls_report=classification_report(y_test,y_pred)

print(cls_report)
input_data=(6,148,72,35,0,33.6,0.627,50)   
input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
std_data = sc.transform(input_data_reshaped)
print(std_data)
prediction=Log.predict(std_data)
print(prediction)
if (prediction[0] == 0):
        print('The person is Non Diabetic')
else:
        print('The person is Diabetic')
 
input_data=(1,85,66,29,0,26.6,0.351,31)   
input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
std_data = sc.transform(input_data_reshaped)
print(std_data)
prediction=Log.predict(std_data)
print(prediction)
if (prediction[0] == 0):
        print('The person is Non Diabetic')
else:
        print('The person is Diabetic')

import pickle
filename = 'model_pickle.pkl'
pickle.dump(Log, open(filename, 'wb'))
